# Generated by Django 2.2.4 on 2020-07-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0001_create_mlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classif_ai.Defect')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classif_ai.MlModel')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='models',
            field=models.ManyToManyField(related_name='defects', through='classif_ai.ModelDefect', to='classif_ai.MlModel'),
        ),
    ]
