# Generated by Django 2.2.4 on 2020-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0002_create_defect'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
