# Generated by Django 2.2.4 on 2020-07-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0004_create_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='classif_ai.FileSet'),
        ),
    ]
