# Generated by Django 2.2.4 on 2020-07-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0006_alter_file_path_in_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_path',
            new_name='path',
        ),
    ]
