# Generated by Django 2.2.4 on 2020-07-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0008_alter_path_in_ml_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='is_stable',
            field=models.BooleanField(default=False),
        ),
    ]
