# Generated by Django 2.2.4 on 2020-07-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0009_alter_default_of_is_stable_in_ml_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='models',
            new_name='ml_models',
        ),
    ]
