# Generated by Django 2.2.4 on 2020-07-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0010_rename_models_to_ml_models_in_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
