# Generated by Django 2.2.4 on 2020-07-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0011_alter_name_and_path_in_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
