# Generated by Django 2.2.4 on 2020-07-30 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classif_ai', '0014_add_fk_to_uploadsession_in_fileset'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_defect_created_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defect',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defect',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_defect_updated_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defect',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_file_created_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_file_updated_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='fileset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_fileset_created_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileset',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_fileset_updated_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileset',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_mlmodel_created_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_mlmodel_updated_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='modeldefect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modeldefect_created_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeldefect',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeldefect',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modeldefect_updated_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeldefect',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_uploadsession_created_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_uploadsession_updated_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
    ]
