# Generated by Django 2.2.4 on 2020-07-31 06:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0016_alter_related_of_upload_session_in_fileset'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='meta_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
