# Generated by Django 2.2.4 on 2020-07-31 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_file_set_meta_info_to_subscription'),
        ('classif_ai', '0017_add_meta_info_to_fileset'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='subscription',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='file_sets', to='subscriptions.Subscription'),
            preserve_default=False,
        ),
    ]
