# Generated by Django 2.2.4 on 2020-08-04 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classif_ai', '0020_add_fk_to_subscription_in_mlmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileset',
            name='meta_info',
        ),
        migrations.CreateModel(
            name='FileSetMetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('field', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=1024)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_filesetmetainfo_created_related', to=settings.AUTH_USER_MODEL)),
                ('file_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_info', to='classif_ai.FileSet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_filesetmetainfo_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
