# Generated by Django 2.2.4 on 2020-08-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0021_create_file_set_meta_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_set_id',
            new_name='file_set',
        ),
    ]
