# Generated by Django 2.2.4 on 2020-08-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0022_rename_file_set_id_to_file_set_in_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileSetMetaInfo',
        ),
    ]
