# Generated by Django 2.2.4 on 2020-08-04 12:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0023_delete_filesetmetainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='meta_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
