# Generated by Django 2.2.4 on 2020-08-04 15:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0024_ad_meta_info_to_fileset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='meta_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
