# Generated by Django 2.2.4 on 2020-08-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0026_add_default_ordering_to_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmodel',
            options={'ordering': ['code']},
        ),
    ]
