# Generated by Django 2.2.4 on 2020-08-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0027_change_default_ordering_of_mlmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='fileset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='mlmodel',
            options={'ordering': ['code', '-id']},
        ),
        migrations.AlterModelOptions(
            name='uploadsession',
            options={'ordering': ['-id']},
        ),
    ]
