# Generated by Django 2.2.4 on 2020-08-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0028_change_default_ordering_to_decreasing_in_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mlmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uploadsession',
            options={},
        ),
    ]
