# Generated by Django 2.2.4 on 2020-08-10 14:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classif_ai', '0029_delete_default_ordering_from_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSetLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('defects', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_filesetlabel_created_related', to=settings.AUTH_USER_MODEL)),
                ('file_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_set_labels', to='classif_ai.FileSet')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_set_labels', to='classif_ai.MlModel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_filesetlabel_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='filesetlabel',
            index=models.Index(fields=['defects'], name='defects_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filesetlabel',
            unique_together={('file_set', 'ml_model')},
        ),
    ]
