# Generated by Django 2.2.4 on 2020-08-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0032_create_file_label_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelabel',
            name='file_set_label',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='file_labels', to='classif_ai.FileSetLabel'),
            preserve_default=False,
        ),
    ]
