# Generated by Django 2.2.4 on 2020-08-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0033_add_fk_to_file_set_label_in_file_label'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filelabel',
            name='file_idx',
        ),
        migrations.RemoveField(
            model_name='filelabelhistory',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filelabelhistory',
            name='ml_model',
        ),
        migrations.AddField(
            model_name='filelabelhistory',
            name='file_set_label',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='file_labels_history', to='classif_ai.FileSetLabel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='filelabel',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='filelabel',
            index=models.Index(fields=['file_set_label'], name='file_set_label_idx'),
        ),
        migrations.RemoveField(
            model_name='filelabel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filelabel',
            name='ml_model',
        ),
    ]
