# Generated by Django 2.2.4 on 2020-08-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0034_remove_file_and_ml_model_in_file_label'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filelabel',
            name='file_set_label_idx',
        ),
        migrations.AlterField(
            model_name='filelabel',
            name='file_set_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_labels', to='classif_ai.FileSetLabel', unique=True),
        ),
    ]
