# Generated by Django 2.2.4 on 2020-08-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0035_add_unique_constraint_to_file_set_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelabel',
            name='file',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='file_labels', to='classif_ai.File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filelabel',
            name='file_set_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_labels', to='classif_ai.FileSetLabel'),
        ),
    ]
