# Generated by Django 2.2.4 on 2020-08-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0036_add_fk_to_file_in_file_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelabel',
            old_name='defect_info',
            new_name='label',
        ),
    ]
