# Generated by Django 2.2.4 on 2020-08-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0037_rename_defect_info_to_label_in_file_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelabelhistory',
            name='file',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='file_labels_history', to='classif_ai.File'),
            preserve_default=False,
        ),
    ]
