# Generated by Django 2.2.4 on 2020-08-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0038_add_fk_to_file_in_file_label_history'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filelabel',
            unique_together={('file', 'file_set_label', 'is_user_feedback')},
        ),
    ]
