# Generated by Django 2.2.4 on 2020-08-12 05:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0039_add_unique_constraint_in_file_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesetlabel',
            name='defects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
