# Generated by Django 2.2.4 on 2020-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0044_add_fk_to_file_region_in_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
