# Generated by Django 2.2.4 on 2020-08-12 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0047_rename_feedbackfileregionhistory_to_fileregionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileregion',
            name='defect_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
