# Generated by Django 2.2.4 on 2020-08-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0049_change_defect_ids_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileregionhistory',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_region_history', to='classif_ai.File'),
        ),
        migrations.AlterField(
            model_name='fileregionhistory',
            name='file_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_region_history', to='classif_ai.FileRegion'),
        ),
        migrations.AlterField(
            model_name='fileregionhistory',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_region_history', to='classif_ai.MlModel'),
        ),
    ]
