# Generated by Django 2.2.4 on 2020-08-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0050_changed_related_names_of_fk_in_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileregion',
            name='ai_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_regions', to='classif_ai.FileRegion'),
        ),
    ]
