# Generated by Django 2.2.4 on 2020-08-12 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classif_ai', '0051_add_blank_true_to_ai_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSetInferenceQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_filesetinferencequeue_created_related', to=settings.AUTH_USER_MODEL)),
                ('file_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_set_inference_queues', to='classif_ai.FileSet')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_set_inference_queues', to='classif_ai.MlModel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_filesetinferencequeue_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
