# Generated by Django 2.2.4 on 2020-08-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0053_change_status_choices_in_inference_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filesetinferencequeue',
            unique_together={('file_set', 'ml_model')},
        ),
    ]
