# Generated by Django 2.2.4 on 2020-08-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0054_add_unique_constraint_in_inference_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, max_length=2056),
        ),
    ]
