# Generated by Django 2.2.4 on 2020-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0055_change_max_length_for_name_and_path_in_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='type',
            field=models.CharField(choices=[('DETECTION', 'Detection'), ('CLASSIFICATION', 'Classification'), ('CLASSIFICATION_AND_DETECTION', 'Detection and Classification')], default='DETECTION', max_length=64),
        ),
    ]
