# Generated by Django 2.2.4 on 2020-08-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0056_add_type_in_ml_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregion',
            name='correctness',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
