# Generated by Django 2.2.4 on 2020-08-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0057_add_correctness_in_file_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileregionhistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
