# Generated by Django 2.2.4 on 2020-08-24 07:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classif_ai', '0058_add_is_deleted_in_file_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('status', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_trainingsession_created_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionFileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('defects', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_trainingsessionfileset_created_related', to=settings.AUTH_USER_MODEL)),
                ('file_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classif_ai.FileSet')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classif_ai.TrainingSession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_trainingsessionfileset_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='file_sets',
            field=models.ManyToManyField(through='classif_ai.TrainingSessionFileSet', to='classif_ai.FileSet'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='new_ml_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='training_session', to='classif_ai.MlModel'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='old_ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classif_ai.MlModel'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_trainingsession_updated_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
