# Generated by Django 2.2.4 on 2020-08-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0058_add_is_deleted_in_file_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileregion',
            name='correctness',
        ),
    ]
