# Generated by Django 2.2.4 on 2020-08-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0059_delete_correctness_in_file_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregion',
            name='classification_correctness',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
