# Generated by Django 2.2.4 on 2020-08-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0059_create_training_session_and_training_session_file_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='path',
        ),
    ]
