# Generated by Django 2.2.4 on 2020-08-24 08:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0060_remove_path_from_ml_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='path',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='training_performance_metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
