# Generated by Django 2.2.4 on 2020-08-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0061_add_detection_corectness_to_file_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileregion',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='fileregion',
            name='is_removed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
