# Generated by Django 2.2.4 on 2020-08-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0062_add_is_removed_to_file_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filesetinferencequeue',
            unique_together=set(),
        ),
    ]
