# Generated by Django 2.2.4 on 2020-08-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0061_add_training_performance_metrics_and_path_to_ml_model'),
        ('classif_ai', '0063_remove_unique_idx_from_fileset_inference_queue'),
    ]

    operations = [
    ]
