# Generated by Django 2.2.4 on 2020-09-02 03:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0064_merge_20200826_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='input_format',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='output_format',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
