# Generated by Django 2.2.4 on 2020-09-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0066_create_usecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='use_case',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='ml_models', to='classif_ai.UseCase'),
            preserve_default=False,
        ),
    ]
