# Generated by Django 2.2.4 on 2020-09-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0068_add_m2m_to_usecase_in_defects_through_usecase_defect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='use_case',
            new_name='use_cases',
        ),
    ]
