# Generated by Django 2.2.4 on 2020-09-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0069_change_use_case_to_use_cases_in_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileregion',
            name='is_removed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
