# Generated by Django 2.2.4 on 2020-09-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0072_add_dataset_train_type_and_belongs_to_old_model_training_data_to_training_session_file_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='old_ml_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classif_ai.MlModel'),
        ),
    ]
