# Generated by Django 2.2.4 on 2020-09-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0073_alter_null_of_old_ml_model_in_training_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='organization_defect_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
