# Generated by Django 2.2.4 on 2020-09-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0073_alter_blank_to_true_in_mlmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usecasedefect',
            unique_together={('use_case', 'defect')},
        ),
    ]
