# Generated by Django 2.2.4 on 2020-10-05 13:31

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0073_alter_null_of_old_ml_model_in_training_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileregion',
            name='classification_correctness',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileregion',
            name='detection_correctness',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileregion',
            name='is_removed',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fileregion',
            name='is_user_feedback',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='fileregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['defects'], name='classif_ai__defects_76249d_gin'),
        ),
    ]
