# Generated by Django 2.2.4 on 2020-10-08 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0074_add_organization_defect_code_to_defects'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='reference_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=None),
        ),
        migrations.AddField(
            model_name='usecasedefect',
            name='reference_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=None),
        ),
    ]
