# Generated by Django 2.2.4 on 2020-10-05 13:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0074_add_indexes_in_file_region'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['meta_info'], name='classif_ai__meta_in_7d5b22_gin'),
        ),
    ]
