# Generated by Django 2.2.4 on 2020-09-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0073_alter_null_of_old_ml_model_in_training_session'),
        ('classif_ai', '0075_add_unique_together_in_ml_model_defect'),
    ]

    operations = [
    ]
