# Generated by Django 2.2.4 on 2020-10-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0075_add_reference_files_to_defect_and_use_case_defect'),
        ('classif_ai', '0075_add_index_on_meta_info_in_file_set'),
    ]

    operations = [
    ]
