# Generated by Django 2.2.4 on 2020-09-30 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0076_merge_20200928_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='old_ml_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classif_ai.MlModel'),
        ),
    ]
