# Generated by Django 2.2.4 on 2020-10-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0077_alter_blank_to_true_of_old_mlmodel_in_training_session'),
        ('classif_ai', '0075_add_index_on_meta_info_in_file_set'),
    ]

    operations = [
    ]
