# Generated by Django 2.2.4 on 2020-10-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0078_create_defect_meta_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='reference_files',
        ),
        migrations.AddField(
            model_name='defect',
            name='reference_files',
            field=models.ManyToManyField(to='classif_ai.File'),
        ),
        migrations.RemoveField(
            model_name='defectmetainfo',
            name='reference_files',
        ),
        migrations.AddField(
            model_name='defectmetainfo',
            name='reference_files',
            field=models.ManyToManyField(to='classif_ai.File'),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='upload_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_sets', to='classif_ai.UploadSession'),
        ),
        migrations.RemoveField(
            model_name='usecasedefect',
            name='reference_files',
        ),
        migrations.AddField(
            model_name='usecasedefect',
            name='reference_files',
            field=models.ManyToManyField(to='classif_ai.File'),
        ),
    ]
