# Generated by Django 2.2.4 on 2020-10-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0079_alter_reference_files_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='classification_type',
            field=models.CharField(choices=[('SINGLE_LABEL', 'Single Label'), ('MULTI_LABEL', 'Multi Label'), ('NOT_APPLICABLE', 'Not Applicable')], default='MULTI_LABEL', max_length=64),
        ),
    ]
