# Generated by Django 2.2.4 on 2020-10-28 10:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0080_mlmodel_classification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
