# Generated by Django 2.2.4 on 2020-10-28 11:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0081_add_image_to_file_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
