# Generated by Django 2.2.4 on 2020-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0083_alter_image_max_length_in_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
