# Generated by Django 2.2.4 on 2020-11-11 04:59

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0085_upload_session_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregion',
            name='model_output_meta_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
