# Generated by Django 2.2.4 on 2020-11-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0087_defect_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='code',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
