# Generated by Django 2.2.4 on 2020-11-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0084_merge_20201104_1925'),
        ('classif_ai', '0088_add_unique_index_to_code_in_defect'),
    ]

    operations = [
    ]
