# Generated by Django 2.2.4 on 2020-12-01 23:19

import common.file_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0089_merge_20201117_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=common.file_storage.TenantFileSystemS3Storage(), upload_to=''),
        ),
    ]
