# Generated by Django 2.2.4 on 2020-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0089_add_unique_index_to_name_in_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('training', 'Training'), ('ready_for_deployment', 'Ready for Deployment'), ('training_failed', 'Training failed'), ('deployed_in_prod', 'Deployed in production'), ('deleted', 'Deleted')], max_length=50),
        ),
    ]
