# Generated by Django 2.2.4 on 2020-11-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0090_alter_choices_for_status_in_ml_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodeldefect',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classif_ai.Defect'),
        ),
        migrations.AlterField(
            model_name='mlmodeldefect',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classif_ai.MlModel'),
        ),
    ]
