# Generated by Django 2.2.4 on 2021-01-07 07:29

import common.file_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0091_auto_20201127_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
