# Generated by Django 2.2.4 on 2020-12-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0091_auto_20201127_0153'),
        ('classif_ai', '0090_alter_image_in_file'),
    ]

    operations = [
    ]
