# Generated by Django 2.2.4 on 2020-12-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0092_merge_20201209_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='upload_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_sets', to='classif_ai.UploadSession'),
        ),
    ]
