# Generated by Django 2.2.4 on 2020-12-10 13:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0093_auto_20201209_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='meta_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
