# Generated by Django 2.2.4 on 2021-01-18 05:42

import common.file_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0093_allow_blank_for_is_bookmarked_in_fileset'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
