# Generated by Django 2.2.4 on 2021-01-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_default_of_file_set_meta_info_in_subscription'),
        ('classif_ai', '0094_add_started_at_finished_at_to_training_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='use_cases', to='subscriptions.Subscription'),
            preserve_default=False,
        ),
    ]
