# Generated by Django 2.2.4 on 2020-12-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0094_move_type_from_mlmodel_to_use_case'),
        ('classif_ai', '0095_alter_on_delete_to_cascade_from_protect'),
    ]

    operations = [
    ]
