# Generated by Django 2.2.4 on 2021-02-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0095_add_subscription_in_use_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
