# Generated by Django 2.2.4 on 2021-02-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0096_add_subscription_fk_to_defects'),
        ('classif_ai', '0096_add_unique_constraint_on_name_in_upload_session'),
    ]

    operations = [
    ]
