# Generated by Django 2.2.4 on 2021-01-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0094_add_started_at_finished_at_to_training_session'),
        ('classif_ai', '0096_merge_20201215_0348'),
    ]

    operations = [
    ]
