# Generated by Django 2.2.4 on 2021-01-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0097_merge_20210126_1743'),
        ('classif_ai', '0095_add_subscription_in_use_case'),
    ]

    operations = [
    ]
