# Generated by Django 2.2.4 on 2021-02-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0096_add_subscription_fk_to_defects'),
        ('classif_ai', '0098_merge_20210127_0231'),
    ]

    operations = [
    ]
