# Generated by Django 2.2.4 on 2021-02-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0099_merge_20210218_0630'),
        ('classif_ai', '0097_merge_20210211_0829'),
    ]

    operations = [
    ]
