# Generated by Django 2.2.4 on 2021-02-25 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0100_merge_20210224_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='use_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_sets', to='classif_ai.UseCase'),
        ),
    ]
