# Generated by Django 2.2.4 on 2021-02-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0101_add_use_case_in_file_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('training', 'Training'), ('ready_for_deployment', 'Ready for Deployment'), ('training_failed', 'Training failed'), ('deployed_in_prod', 'Deployed in production'), ('deleted', 'Deleted'), ('user_terminated', 'Terminated by user')], max_length=50),
        ),
    ]
