# Generated by Django 2.2.4 on 2021-03-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0102_add_extra_status_choice_in_ml_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='use_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='classif_ai.UseCase'),
        ),
    ]
