# Generated by Django 2.2.4 on 2021-03-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0103_add_use_case_in_upload_session'),
        ('classif_ai', '0098_create_ml_model_deployment_history'),
    ]

    operations = [
    ]
