# Generated by Django 3.0.9 on 2021-04-20 08:26

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0108_add_is_bookmarked_to_upload_session'),
    ]

    operations = [
        TrigramExtension(),
    ]
