# Generated by Django 3.0.9 on 2021-04-20 09:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0109_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='file_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
