# Generated by Django 3.0.9 on 2021-04-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0110_add_index_to_name_in_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='reference_files',
            field=models.ManyToManyField(related_name='referenced_defects', to='classif_ai.File'),
        ),
    ]
