# Generated by Django 2.2.4 on 2021-04-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0111_auto_20210421_0336'),
        ('classif_ai', '0114_switch_use_case_name_to_cit'),
    ]

    operations = [
    ]
