# Generated by Django 3.2 on 2021-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0115_merge_20210421_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectmetainfo',
            name='meta_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='fileregion',
            name='defects',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='fileregion',
            name='model_output_meta_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fileregion',
            name='region',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='fileregionhistory',
            name='defects',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='fileregionhistory',
            name='region',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='meta_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='input_format',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='output_format',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='path',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='training_performance_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trainingsessionfileset',
            name='defects',
            field=models.JSONField(default=dict),
        ),
    ]
