# Generated by Django 3.2 on 2021-09-07 06:16

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classif_ai', '0119_create_gt_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('is_no_defect', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modelclassification_created_related', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_classifications', to='classif_ai.file')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_classification_models', to='classif_ai.mlmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modelclassification_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file', 'ml_model')},
            },
        ),
        migrations.CreateModel(
            name='ModelDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('is_no_defect', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modeldetection_created_related', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_detections', to='classif_ai.file')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_detection_models', to='classif_ai.mlmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modeldetection_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file', 'ml_model')},
            },
        ),
        migrations.CreateModel(
            name='ModelDetectionRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('region', django.contrib.gis.db.models.fields.GeometryField(srid=3857)),#https://epsg.io/3857, unit is in metre unlike 4326 where unit is in degrees; both still use coordinate systems to annotate on the map
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modeldetectionregion_created_related', to=settings.AUTH_USER_MODEL)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_detection_regions', to='classif_ai.modeldetection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modeldetectionregion_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('detection', 'region')},
            },
        ),
        migrations.CreateModel(
            name='ModelDetectionRegionDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_detection_region_defects', to='classif_ai.defect')),
                ('detection_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_detection_region_annotations', to='classif_ai.modeldetectionregion')),
            ],
            options={
                'unique_together': {('detection_region', 'defect')},
            },
        ),
        migrations.CreateModel(
            name='ModelClassificationDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_classification_annotations', to='classif_ai.modelclassification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modelclassificationdefect_created_related', to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_classification_defects', to='classif_ai.defect')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classif_ai_modelclassificationdefect_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classification', 'defect')},
            },
        ),
    ]
