# Generated by Django 3.2 on 2021-09-14 10:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0120_create_model_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclassification',
            name='defects',
            field=models.ManyToManyField(related_name='user_classifications', through='classif_ai.UserClassificationDefect', to='classif_ai.Defect'),
        ),
    ]
