# Generated by Django 3.2 on 2021-09-15 06:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0121_auto_20210914_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelclassification',
            name='defects',
            field=models.ManyToManyField(related_name='model_classifications', through='classif_ai.ModelClassificationDefect', to='classif_ai.Defect'),
        )
    ]
