# Generated by Django 3.2 on 2021-09-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0122_auto_20210915_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='confidence_threshold',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='modelclassificationdefect',
            name='confidence',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='modeldetectionregion',
            name='defects',
            field=models.ManyToManyField(related_name='model_detection_regions', through='classif_ai.ModelDetectionRegionDefect', to='classif_ai.Defect'),
        ),
        migrations.AddField(
            model_name='modeldetectionregiondefect',
            name='confidence',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='modeldetectionregion',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_regions', to='classif_ai.modeldetection'),
        ),
    ]
