# Generated by Django 3.2 on 2021-09-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0123_auto_20210915_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetectionregiondefect',
            name='detection_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_defects', to='classif_ai.modeldetectionregion'),
        ),
    ]
