# Generated by Django 3.2 on 2021-09-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0124_alter_detection_region_to_model_detection_region_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetectionregion',
            name='model_output_meta_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
