# Generated by Django 3.2 on 2021-09-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0126_rename_related_name_for_detection_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='classification_type',
            field=models.CharField(choices=[('SINGLE_LABEL', 'Single Label'), ('MULTI_LABEL', 'Multi Label')], default='MULTI_LABEL', max_length=64),
        ),
    ]
