# Generated by Django 3.2 on 2021-09-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0126_rename_related_name_for_detection_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetectionregion',
            name='defects',
            field=models.ManyToManyField(related_name='user_detection_regions', through='classif_ai.UserDetectionRegionDefect', to='classif_ai.Defect'),
        ),
    ]
