# Generated by Django 3.2 on 2021-09-17 01:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    MlModel = apps.get_model("classif_ai", "MlModel")
    db_alias = schema_editor.connection.alias
    for ml_model in MlModel.objects.using(db_alias).all():
        use_case = ml_model.use_case
        use_case.classification_type = ml_model.classification_type
        use_case.save()


def backwards_func(apps, schema_editor):
    UseCase = apps.get_model("classif_ai", "UseCase")
    db_alias = schema_editor.connection.alias
    for use_case in UseCase.objects.using(db_alias).all():
        for ml_model in use_case.ml_models.all():
            ml_model.classification_type = use_case.classification_type
            ml_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0127_add_classification_type_in_use_case'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func, atomic=True),
    ]
