# Generated by Django 3.2 on 2021-09-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0127_add_defects_as_m2m_in_user_detection_region'),
        ('classif_ai', '0129_drop_classification_type_in_ml_model'),
    ]

    operations = [
    ]
