# Generated by Django 3.2 on 2021-10-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0132_migrate_data_from_file_region_to_new_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtclassification',
            name='defects',
            field=models.ManyToManyField(related_name='gt_classifications', through='classif_ai.GTClassificationDefect', to='classif_ai.Defect'),
        ),
    ]
