# Generated by Django 3.2 on 2021-11-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0133_gtclassification_defects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('training', 'Training'), ('ready_for_deployment', 'Ready for Deployment'), ('training_failed', 'Training failed'), ('deployed_in_prod', 'Deployed in production'), ('deleted', 'Deleted'), ('user_terminated', 'Terminated by user'), ('retired', 'Retied after deployment')], max_length=50),
        ),
    ]
