# Generated by Django 3.2 on 2021-11-25 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0135_create_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaferMapTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classif_ai.tag')),
                ('wafer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classif_ai.wafermap')),
            ],
        ),
        migrations.AddField(
            model_name='wafermap',
            name='tags',
            field=models.ManyToManyField(related_name='wafer_maps', through='classif_ai.WaferMapTag', to='classif_ai.Tag'),
        ),
    ]
