# Generated by Django 3.2 on 2021-12-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0135_add_on_hold_wafermap'),
        ('classif_ai', '0136_create_wafermap_tags'),
    ]

    operations = [
    ]
