# Generated by Django 3.2 on 2021-12-10 11:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0137_merge_20211202_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wafermap',
            name='on_hold',
        ),
        migrations.AddField(
            model_name='wafermap',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('auto_classified', 'Auto Classified'), ('manual_classification_pending', 'Manual classification pending'), ('manually_classified', 'Manually Classified')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='fileset',
            name='wafer_location',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857),
        ),
        migrations.AddField(
            model_name='wafermap',
            name='img_meta_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wafermap',
            name='wafer_url',
            field=models.URLField(blank=True, null=True),
        )
    ]
