# Generated by Django 3.2 on 2021-12-30 09:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0138_add_status_wafermap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileset',
            old_name='wafer_location',
            new_name='location_on_wafer',
        )
    ]
