# Generated by Django 3.2 on 2022-01-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0139_rename_wafer_location_to_location_on_wafer'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesetinferencequeue',
            name='inference_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='artifact_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='inference_endpoint',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='inference_endpoint_region',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
