# Generated by Django 3.2 on 2022-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0140_add_inference_endpoint_to_mlmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wafermap',
            name='wafer_url',
        ),
        migrations.AddField(
            model_name='wafermap',
            name='image_path',
            field=models.CharField(blank=True, max_length=2056),
        ),
    ]
