# Generated by Django 3.2 on 2022-01-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0142_added_coordinate_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='wafermap',
            name='defect_pattern_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wafermap',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('auto_classified', 'Auto Classified'), ('manual_classification_pending', 'Manual classification pending'), ('manually_classified', 'Manually Classified')], default='pending', max_length=50),
        ),
    ]
