# Generated by Django 3.2 on 2022-01-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classif_ai', '0143_added_defect_pattern_info_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('training', 'Training'), ('ready_for_deployment', 'Ready for Deployment'), ('training_failed', 'Training failed'), ('deployed_in_prod', 'Deployed in production'), ('deleted', 'Deleted'), ('user_terminated', 'Terminated by user'), ('retired', 'Retied after deployment')], max_length=50),
        ),
    ]
