# Generated by Django 2.2.4 on 2020-08-04 15:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_file_set_meta_info_to_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='file_set_meta_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
