# Generated by Django 2.2.4 on 2021-04-07 10:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_default_of_file_set_meta_info_in_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='overkill_defect_config',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
