# Generated by Django 3.2 on 2021-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_blank_to_meta_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='file_set_meta_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
