# Generated by Django 3.2 on 2021-12-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_switch_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expected_automation',
            field=models.FloatField(default=0.93),
        ),
    ]
