# Generated by Django 2.2.4 on 2021-01-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_modify_image_in_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='category',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend')], default='BACKEND', max_length=20),
        ),
    ]
