# Generated by Django 2.2.4 on 2021-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_add_category_to_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='image_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pack',
            name='manufacturing',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pack',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='process',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
