# Generated by Django 2.2.4 on 2021-01-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_auto_20210126_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='objective',
        ),
    ]
