# Generated by Django 3.2 on 2022-01-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_updated_parameters_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationscenario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
